local m = require('plugins.snippets.shorts')

return {
    m.s('competitive', {
        m.t({
            '#include <bits/stdc++.h>',
            '',
            '#define ALL(v) v.begin(), v.end()',
            '#define vi vector<int>',
            '#define pii pair<int, int>',
            '',
            'using namespace std;',
            '',
            'using ll = long long;',
            'using ull = unsigned long long;',
            'using ld = long double;',
            '',
            'template<typename T, typename J>',
            'istream &operator>>(istream &in, pair<T, J> &a) {',
            '\tin >> a.first >> a.second;',
            '\treturn in;',
            '}',
            '',
            'template<typename T>',
            'istream &operator>>(istream &in, vector<T> &a) {',
            '\tfor (int i = 0; i < a.size(); ++i)',
            '\t\tin >> a[i];',
            '\treturn in;',
            '}',
            '',
            'template<typename T>',
            'ostream &operator<<(ostream &out, vector<T> &a) {',
            '\tfor (int i = 0; i < a.size(); ++i)',
            '\t\tout << a[i] << \' \';',
            '\treturn out;',
            '}',
            '',
            'void solve() {',
            '\t',
        }),
        m.i(2),
        m.t({
            '',
            '}',
            '',
            'int main() {',
            '#ifdef _DEBUG',
            '\tfreopen("input.txt", "r", stdin);',
            '\tfreopen("output.txt", "w", stdout);',
            '#endif',
            '\tios::sync_with_stdio(false);',
            '\tcin.tie(nullptr), cout.tie(nullptr);',
            '\tcout.precision(32);',
            '\tint t = 1;',
            '\t//',
        }),
        m.i(1),
        m.t({
            'cin >> t;',
            '\twhile (t--) {',
            '\t\tsolve();',
            '\t}',
            '}',
        })
  }),
}
